### PR TITLE
Treat no method errors as not comparable

### LINKED ISSUE #971: Comparison matchers fail poorly when compared against non-comparable object
Example:

``` ruby
expect(foo: nil).to include(foo: a_value > 10)
```

Results in:

```
     Failure/Error: expect(foo: nil).to include(foo: a_value > 10)

     NoMethodError:
       undefined method `>' for nil:NilClass
```

Instead of trying to check `nil > 10` and getting an error, it should only run the comparison if `actual.respond_to?(:>)` and return `false` if it is non-comparable.

### PR DESCRIPTION
**Pull request by JonRowe**
Fixes #971

### CODE REVIEW

File: spec/rspec/matchers/built_in/contain_exactly_spec.rb [hunk 1]
```diff
@@ -105,6 +105,10 @@ def array.send; :sent; end
     }.to fail_with(/expected collection contained/)
   end
 
+  it 'works with hashes' do
+    expect([{ :a => 1 }]).to_not contain_exactly({ :a => 1 }, { :a => 2 }) 
+  end
```
Comment (myronmarston) [inline spec/rspec/matchers/built_in/contain_exactly_spec.rb]: What does this spec have to do with the rest of this PR?  Seems completely unrelated...

Comment (JonRowe) [inline spec/rspec/matchers/built_in/contain_exactly_spec.rb]: Nothing, evidently I did a `git ci -a` oops :)

**Comment by JonRowe** [comment]
Merging as only change was removing unrelated spec.
