### PR TITLE
Use `hash` for `change` matcher to handle deeply nested objects.

### LINKED ISSUE #1030: 'change' matcher using incorrect initial value (with Vectors nested in arrays)
When using vectors nested inside a hash inside an array the change matcher appears to take the resulting value as the initial value.

For example;

```ruby
require 'matrix'

RSpec.describe 'vectors' do
  let(:vectors) { [{ a: Vector[1, 2] }] }

  it 'adds to the vector' do
    expect { vectors[0][:a] += Vector[1, 1] }
      .to change{vectors}
      .from( [{a: Vector[1, 2] }] )
      .to( [{a: Vector[2, 3]}] )
  end
end
```

When I run this test I get:

```
Failures:

  1) vectors adds to the vector
     Failure/Error:
       expect { vectors[0][:a] += Vector[1, 1] }
         .to change{vectors}
         .from( [{a: Vector[1, 2] }] )
         .to( [{a: Vector[2, 3]}] )

       expected `vectors` to have initially been [{:a=>Vector[1, 2]}], but was [{:a=>Vector[2, 3]}]
     # ./spec/test_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.02426 seconds (files took 0.12668 seconds to load)
1 example, 1 failure
```

If I remove the `from` section I then get a failure saying that `vectors` did not change.

I am using rspec 3.7.0 and Ruby 2.4.1

### PR DESCRIPTION
**Pull request by myronmarston**
Fixes #1030.

### CODE REVIEW

**Comment by myronmarston** [comment]
This is ready for review /cc @rspec/rspec.

The travis failure is only for 1.9.3, and is related to the rspec-rails build, due to a rake version mismatch.  I've attempted a fix in rspec/rspec-rails#1935.

**Comment by myronmarston** [comment]
Not sure why appveyor isn't building, but it was green before I rebased against master, and now travis is green, too.  Anyone from @rspec/rspec up for reviewing this?

File: lib/rspec/matchers/built_in/change.rb [hunk 1]
```diff
@@ -312,8 +322,20 @@ def change_description
...
+      #
+      # Note that this class exposes the `actual_after` value, to allow the
+      # matchers above to derive failure messages, etc from the value on demand
+      # as needed, but it intentionally does _not_ expose the `actual_before`
+      # value. Some usages of the `change` matcher mutate a specific object
+      # returned by the value proc, which means that failure message snippets,
+      # etc, which are derived from the `before` value may not be accurate if
+      # they are lazily computed as needed. We must pre-compute them before
+      # applying the change in the `expect` block. To ensure that all `change`
+      # matchers do that properly, we do not expeose the `actual_before` value.
```
Comment (xaviershay) [inline lib/rspec/matchers/built_in/change.rb]: nit: typo on expeose

File: lib/rspec/matchers/built_in/change.rb [hunk 2]
```diff
@@ -344,12 +366,29 @@ def value_representation
...
-          @actual_before != @actual_after
+          # Consider it changed if either:
+          #
+          # - The before/after values are unequal
+          # - The before/after values have different hash values
+          #
+          # The latter case specifically handles the case when the value proc
+          # returns the exact same object, but it has been mutated.
+          #
+          # Note that is is not sufficient to only check the hashes; it is
```
Comment (xaviershay) [inline lib/rspec/matchers/built_in/change.rb]: nit "is is" typo

File: lib/rspec/matchers/built_in/change.rb [hunk 3]
```diff
@@ -359,16 +398,7 @@ def actual_delta
       private
 
         def evaluate_value_proc
-          value_proc = @value_proc || lambda { @receiver.__send__(@message) }
-
-          case val = value_proc.call
```
Comment (xaviershay) [inline lib/rspec/matchers/built_in/change.rb]: glad we could get rid of this

File: lib/rspec/matchers/built_in/change.rb [hunk 4]
```diff
@@ -344,12 +366,29 @@ def value_representation
 
         def perform_change(event_proc)
           @actual_before = evaluate_value_proc
+          @before_hash = @actual_before.hash
+          yield @actual_before if block_given?
+
+          return false unless Proc === event_proc
```
Comment (xaviershay) [inline lib/rspec/matchers/built_in/change.rb]: not obvious to me why this was added/needed? When is a non-`Proc` passed?

Comment (xaviershay) [reply lib/rspec/matchers/built_in/change.rb]: oh, it might be `nil` with some invocations, though in that case why not check for that directly?

Comment (myronmarston) [reply lib/rspec/matchers/built_in/change.rb]: It an be anything, if a user tries to use it as a value matcher instead of a block matcher, e.g.:

``` ruby
expect(3).to change { ... }
expect(:foo).to change { ... }
```

In these cases, `event_proc` will be `3` and `:foo`, respectively.

Anyhow, this check wasn't actually added; it was moved as part of the diff.

File: lib/rspec/matchers/built_in/change.rb (hunk 3 above)
Comment (myronmarston) [reply lib/rspec/matchers/built_in/change.rb]: Me too.  The dup'ing always felt dirty :(.

File: lib/rspec/matchers/built_in/change.rb (hunk 1 above)
Comment (myronmarston) [reply lib/rspec/matchers/built_in/change.rb]: Good catch, fixed.

File: lib/rspec/matchers/built_in/change.rb (hunk 2 above)
Comment (myronmarston) [reply lib/rspec/matchers/built_in/change.rb]: Good catch, fixed.

**Comment by myronmarston** [comment]
Thanks for the review, @xaviershay.  I pushed fixes for the typos and will merge once the build finishes.
