### PR TITLE
expose fail matchers for testing custom matchers

### LINKED ISSUE #652: Testing custom matchers
Had hoped to find documentation pointing out some good examples of how to do this but ended up just having to look through the source code to see how rspec was doing it.

```ruby
# located in spec/support/matchers.rb

module RSpec
  module Matchers
    def fail
      raise_error(RSpec::Expectations::ExpectationNotMetError)
    end

    def fail_with(message)
      raise_error(RSpec::Expectations::ExpectationNotMetError, message)
    end

    def fail_matching(message)
      if String === message
        regexp = /#{Regexp.escape(message)}/
      else
        regexp = message
      end
      raise_error(RSpec::Expectations::ExpectationNotMetError, regexp)
    end
  end
end
```
Would apprecite two things that I am happy to help out with:
1. Documentation added about testing custom methods
2. Expose the above snippet being a built in matcher or possible to include it easily with something like `require 'rspec/matchers/fail'` (@myronmarston already noted that `fail` is a core ruby method so may be better to rename to `fail_expectation`)

### PR DESCRIPTION
**Pull request by charlierudolph**
@myronmarston

resolves #652

### CODE REVIEW

**Comment by myronmarston** [comment]
As discussed in #652, the `fail` matcher conflicts with `Kernel#fail`, so these can't simply be added directly to `RSpec::Matchers` -- in fact, that's what's causing the travis failure as it runs the other rspec repos' spec suites to see if the changes breaks anything and there are several rspec-core specs that use `fail` to fail an example by raising an error.  Making `fail` return a matcher makes those specs no longer behave as expected.

So, this really needs to be pulled out into a separate file that users can require and include themselves if needed.

File: lib/rspec/matchers.rb [hunk 1]
```diff
@@ -745,6 +745,38 @@ def raise_error(error=Exception, message=nil, &block)
...
+    def fail_with(message)
+      raise_error(RSpec::Expectations::ExpectationNotMetError, message)
+    end
+
+    # Matches if an expectation fails including the provided message
+    #
+    # @example
+    #
+    #   expect { some_expectation }.to fail_including("some failure message")
+    #   expect { some_expectation }.to fail_including(/some failure message/)
```
Comment (myronmarston) [inline lib/rspec/matchers.rb]: Passing a regex to `fail_including` doesn't make any sense.  Use `fail_with` if you're using a regex (as that will match properly), but the regex will not work here because a string does not _include_ a regex, it _matches_ one.  (OTOH, if the message was an array containing regex -- such as `[/some regex/]` -- then it could work, but it's not, so the regex example is nonsensical).

File: lib/rspec/matchers.rb [hunk 2]
```diff
@@ -745,6 +745,38 @@ def raise_error(error=Exception, message=nil, &block)
...
+    #
+    #   expect { some_expectation }.to fail
+    def fail
+      raise_error(RSpec::Expectations::ExpectationNotMetError)
+    end
+
+    # Matches if an expectation fails with the provided message
+    #
+    # @example
+    #
```
Comment (myronmarston) [inline lib/rspec/matchers.rb]: Please remove these blank lines between `@example` and the example code.  YARD assumes the code starts on the immediate next line and when you have a blank line it renders it, too, which is unnecessary and looks odd.

**Comment by charlierudolph** [comment]
@myronmarston all comments addressed. If I put `require 'rspec/matchers/fail_matchers'` at the top of the support file, it errored with
```
/rspec-expectations/spec/support/matchers.rb:3:in `<top (required)>': undefined method `define' for RSpec::Matchers:Module (NoMethodError)
	from /rspec-expectations/spec/spec_helper.rb:8:in `require'
	from /rspec-expectations/spec/spec_helper.rb:8:in `block in <top (required)>'
	from /rspec-expectations/spec/spec_helper.rb:7:in `each'
	from /rspec-expectations/spec/spec_helper.rb:7:in `<top (required)>'
```  
Any idea what would cause that?

**Comment by myronmarston** [comment]
> Any idea what would cause that?

Yep.  rspec-core has some logic to load rspec-expectations on the first reference of `RSpec::Matchers` (in addition to the rspec-core config system loading it an appropriate time before running the first example group):

https://github.com/rspec/rspec-core/blob/v3.2.0/lib/rspec/core.rb#L167-L188

That only works when `const_missing` is triggered, which no longer happens because `rspec/matchers/fail_matchers` defines the `RSpec::Matchers` module, but the rest of the library hasn't been loaded.  You can fix this by explicitly requiring `rspec/expectations` in `spec/support/matchers.rb`.

**Comment by myronmarston** [comment]
Can you squash this into one commit?

**Comment by charlierudolph** [comment]
@myronmarston done

File: spec/support/matchers.rb [hunk 3]
```diff
@@ -1,3 +1,6 @@
+require 'rspec/expectations'
```
Comment (JonRowe) [inline spec/support/matchers.rb]: I'm thinking this require should be inside the `rspec/matchers/fail_matchers` file...

Comment (myronmarston) [inline spec/support/matchers.rb]: That's a good point -- if users `require 'rspec/matchers/fail_matchers` and then try `RSpec::Matchers.define` they would run into the same issue.  So I agree with @JonRowe.

Comment (JonRowe) [inline spec/support/matchers.rb]: And resquash if you wouldn't mind :) (sorry should have spotted earlier)

**Comment by charlierudolph** [comment]
@myronmarston @JonRowe updated. The test failure appears to be unrelated (bad file descriptor) and I don't see anywhere that would allow me to rebuild.

**Comment by myronmarston** [comment]
@JonRowe -- planning to add a changelog entry for this?

**Comment by JonRowe** [comment]
Yes
