### PR TITLE
Emit a special warning when `nil` is passed to `raise_error`

### LINKED ISSUE #1142: Unintentional passing of `nil` to `raise_error`
### Subject of the issue

We issue a warning when `raise_error` is called with no exception class and no block:
> Instead consider providing a specific error class or message

However, it's hard to imagine why would someone explicitly pass a `nil` as an exception class.
I've stumbled across a situation when this is done unitentionally:

```ruby
let(:status_code_exception_mapping) { {404: SomethingNotFound} }
let(:expected_exception_class) do
  status_code_exception_mapping[status_code]
end
let(:status_code) { 502 }

it "raises a specific error" do
  expect { process! }
    .to raise_error(expected_exception_class)
end
```

In this example, a `raise_error(nil)` was called, even though it wasn't at all obvious since `status_code_exception_mapping` was buried in the code.
What made it even worse is that there was an exception of a different type raised, and the only way to notice that was the warning about possible exception mismatch.

This was hiding a real exception that was way different from anything expected.

### Your environment
* Ruby version: 2.5.1
* rspec-expectations version: 3.6.0 (however, glancing over the latest code it seems that the behaviour has not changed)

### Steps to reproduce

```
# spec/a_spec.rb
RSpec.describe do
  it "raises a specific error" do
    expect { process! }
      .to raise_error(nil)
  end
end
```

### Expected behavior

Error message resulting in spec failure, something like:
> `nil` is not a valid value for an expected exception.

I would expect it to be raised disregarding `on_potential_false_positives` setting.

### Actual behavior

```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call.
Actual error raised was #<TypeError: no implicit conversion of Hash into String>.
Instead consider providing a specific error class or message.
This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`.
Called from ...
```

### Proposed solution

Use
```ruby
      UndefinedValue = Module.new
```
to make a distinction between `raise_error()` and `raise_error(nil)`.

### Open questions

Is this a breaking change? Should this target 4.0?

### PR DESCRIPTION
**Pull request by pirj**
Usage of `nil` with `raise_error` is with a high chance unintentional, including negation.

Fixes #1142

### CODE REVIEW

File: lib/rspec/matchers/built_in/raise_error.rb [hunk 1]
```diff
@@ -9,13 +9,20 @@ module BuiltIn
...
+        # argument. We can't use `nil` for that because we need to warn when `nil` is
+        # passed in a different way. It's an Object, not a Module, since Module's `===`
+        # does not evaluate to true when compared to itself.
+        UndefinedValue = Object.new
+
+        def initialize(expected_error_or_message, expected_message, &block)
           @block = block
           @actual_error = nil
-          @warn_about_bare_error = expected_error_or_message.nil?
+          @warn_about_bare_error = UndefinedValue.equal?(expected_error_or_message)
```
Comment (JonRowe) [inline lib/rspec/matchers/built_in/raise_error.rb]: A `===` is more our style here...

File: lib/rspec/matchers/built_in/raise_error.rb [hunk 2]
```diff
@@ -9,13 +9,20 @@ module BuiltIn
       class RaiseError
         include Composable
 
-        def initialize(expected_error_or_message=nil, expected_message=nil, &block)
+        # Used as a sentinel value to be able to tell when the user did not pass an
+        # argument. We can't use `nil` for that because we need to warn when `nil` is
+        # passed in a different way. It's an Object, not a Module, since Module's `===`
+        # does not evaluate to true when compared to itself.
```
Comment (JonRowe) [inline lib/rspec/matchers/built_in/raise_error.rb]: 👍Great explanation. Perhaps freeze the object too?

File: lib/rspec/matchers/built_in/raise_error.rb [hunk 3]
```diff
@@ -166,11 +177,37 @@ def warn_about_bare_error
...
+                         "any other error would cause the expectation to pass, including " \
+                         "those raised by Ruby (e.g. `NoMethodError`, `NameError` and " \
+                         "`ArgumentError`), meaning the code you are intending to test may " \
+                         "not even get reached. " \
+                         "Instead consider using `expect { }.not_to raise_error` or " \
+                         "`expect { }.to raise_error(DifferentSpecificErrorClass)`. " \
+                         "This message can be suppressed by setting: " \
+                         "`RSpec::Expectations.configuration.on_potential_false" \
+                         "_positives = :nothing`")
+        end
```
Comment (JonRowe) [inline lib/rspec/matchers/built_in/raise_error.rb]: Would this not be the same as the original negative error warning?

File: lib/rspec/matchers/built_in/raise_error.rb [hunk 4]
```diff
@@ -166,11 +177,37 @@ def warn_about_bare_error
...
+                         "unintentional, it risks false positives, since `raise_error` " \
+                         "will match when Ruby raises a `NoMethodError`, `NameError` or " \
+                         "`ArgumentError`, potentially allowing the expectation to pass " \
+                         "without even executing the method you are intending to call. " \
+                         "#{warning}"\
+                         "Instead consider providing a specific error class or message. " \
+                         "This message can be suppressed by setting: " \
+                         "`RSpec::Expectations.configuration.on_potential_false" \
+                         "_positives = :nothing`")
+        end
```
Comment (JonRowe) [inline lib/rspec/matchers/built_in/raise_error.rb]: Risks or will cause? :joy:

File: lib/rspec/matchers.rb [hunk 5]
```diff
@@ -761,20 +761,22 @@ def output(expected=nil)
...
     #   expect { do_something_risky }.to raise_error(PoorRiskDecisionError, /oo ri/)
+    #   expect { do_something_risky }.to raise_error("that was too risky")
     #
     #   expect { do_something_risky }.not_to raise_error
-    def raise_error(error=nil, message=nil, &block)
+    def raise_error(error=BuiltIn::RaiseError::UndefinedValue, message=nil, &block)
       BuiltIn::RaiseError.new(error, message, &block)
     end
-    alias_method :raise_exception,  :raise_error
+    alias_method :raise_exception,   :raise_error
```
Comment (JonRowe) [inline lib/rspec/matchers.rb]: Honestly we should just change all these to `, :` rather than trying to align them.

File: lib/rspec/matchers/built_in/raise_error.rb (hunk 3 above)
Comment (JonRowe) [reply lib/rspec/matchers/built_in/raise_error.rb]: I mean could you not do this with `warn_about_negative_false_positive!("raise_error(nil)")`

Comment (pirj) [reply lib/rspec/matchers/built_in/raise_error.rb]: I've added this distinctive message intentionally. First off, I don't think anyone would deliberately write `.not_to raise_error(nil)`, so there should be some kind of mistake, and a regular message telling that didn't pass anything to `raise_error` and they'd better use `raise_error(DifferentSpecificErrorClass)` might be confusing and would suggest an idea of an RSpec bug, since they obviously passed something. Another point was to make it more visible to remind us that we planned to switch it to raise an error eventually.
Do you think it's reasonable enough to keep a separate message?

Comment (JonRowe) [reply lib/rspec/matchers/built_in/raise_error.rb]: > I've added this distinctive message intentionally.

Except it's not distinct? It's identical except for swapping `#{expression}` for `raise_error(nil)` so why not set expression to `"raise_error(nil)"` and generate the same string using the existing method?

Comment (pirj) [reply lib/rspec/matchers/built_in/raise_error.rb]: Sorry for the delay in getting your idea. Fixed, it turns out to be more concise the way you suggested 👍

**Comment by JonRowe** [comment]
Do you want to a change log for this @pirj? Or shall I?

**Comment by pirj** [comment]
Added in [704f0a26](https://github.com/rspec/rspec-expectations/commit/704f0a26).

**Comment by pirj** [comment]
I've received a notification about a note, but the author removed the note. Presumably from @mathieujobin or @mjobin-mdsol.

> I wonder if via a config option, we could make this raise an InvalidError instead of a simple warning...

Adding such an option makes total sense to me.

Would you like to send a PR to `main` to make this configurable?

If you want to go a step further and raise an exception (I'd go with `ArgumentError`), you can also:
 - send another PR to `main`, but targeting the release [3.99](https://github.com/rspec/rspec-expectations/milestone/10) that would warn users that the option will be removed, and the exception would become the default
 - send a PR to [`4-0-dev`](https://github.com/rspec/rspec-expectations/tree/4-0-dev) with removal of the option and making `ArgumentError` the default behaviour

@JonRowe Do you support the idea?

**Comment by mjobin-mdsol** [comment]
Thanks for the ping @pirj 

I can't commit to open a PR with a new config options, I'm sorry. But I created a branch on my end for testing existing projects

https://github.com/mjobin-mdsol/rspec-expectations/commit/140845384f39c5b36a5b63e7ea2f95e5dd85bcef

**Comment by JonRowe** [comment]
@pirj I'm happy for this idea to be a thing if someone wants to make it so.
