### PR TITLE
Fix #1160 - aggregate_failures without line path

### LINKED ISSUE #1160: The method aggregate_failures isn't showing the lines of the failures like rspec-core
### Subject of the issue
When I add the method aggregate_failures in my expects on Cucumber, it isn't showing the lines of the failures, just the line of the block aggregate_failures.
If you look at [RSpec Core - aggregate_failures](https://relishapp.com/rspec/rspec-core/v/3-9/docs/expectation-framework-integration/aggregating-failures#enable-failure-aggregation-globally-using-%60define-derived-metadata%60) you can see the lines of each failure, but if you look at [RSpec Expectations - aggregate_failures](https://relishapp.com/rspec/rspec-expectations/docs/aggregating-failures) it shows only the failures without the lines.

### Your environment
* Ruby version: 2.6.0
* rspec-expectations version: 3.9.0

### Steps to reproduce
```
17.  Then 'validate the return of the endpoint xyz' do
18.    aggregate_failures do
19.      expect(response.status).to eq(200)
20.      expect(response.headers).to include("Content-Type" => "application/json")
21.      expect(response.body).to eq('{"message":"Success"}')
22.    end
23.  end
```

### Expected behavior
```
Failures:
  1) Client returns a successful response
     Got 3 failures:

     1.1) Got 3 failures from failure aggregation block "testing response".
          # ./spec/use_block_form_spec.rb:18
          # ./spec/use_block_form_spec.rb:10

          1.1.1) Failure/Error: expect(response.status).to eq(200)

                   expected: 200
                        got: 404

                   (compared using ==)
                 # ./spec/use_block_form_spec.rb:19

          1.1.2) Failure/Error: expect(response.headers).to include("Content-Type" => "application/json")
                   expected {"Content-Type" => "text/plain"} to include {"Content-Type" => "application/json"}
                   Diff:
                   @@ -1,2 +1,2 @@
                   -"Content-Type" => "application/json",
                   +"Content-Type" => "text/plain",
                 # ./spec/use_block_form_spec.rb:20

          1.1.3) Failure/Error: expect(response.body).to eq('{"message":"Success"}')

                   expected: "{\"message\":\"Success\"}"
                        got: "Not Found"

                   (compared using ==)
                 # ./spec/use_block_form_spec.rb:21
```

### Actual behavior
```
Got 3 failures from failure aggregation block "testing response":

  1) expected: 200
          got: 404

     (compared using ==)

  2) expected: "application/json"
          got: "text/plain"

     (compared using ==)

  3) expected: "{\"message\":\"Success\"}"
          got: "Not Found"

     (compared using ==)
```

### PR DESCRIPTION
**Pull request by fabriciobedin**
https://github.com/rspec/rspec-expectations/issues/1160

changed from this return
```
Got 3 failures from failure aggregation block:

1) expected 1.eql?(2) to return true, got false

2) expected 2.eql?(3) to return true, got false

3) expected 3.eql?(4) to return true, got false (RSpec::Expectations::MultipleExpectationsNotMetError)
./features/steps_definitions/test_aggregate_failures_steps.rb:16:in 'some scenario description'
features/gherkins/test_aggregate_failures.feature:5:in '* some scenario description'
```

to it
```
Got 3 failures from failure aggregation block:

1) expected 1.eql?(2) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:28

2) expected 2.eql?(3) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:29

3) expected 3.eql?(4) to return true, got false
./features/steps_definitions/test_aggregate_failures_steps.rb:31

(RSpec::Expectations::MultipleExpectationsNotMetError)
./features/steps_definitions/test_aggregate_failures_steps.rb:27:in 'some scenario description'
features/gherkins/test_aggregate_failures.feature:5:in '* some scenario description'
```

### CODE REVIEW

**Comment by fabriciobedin** [comment]
The build is failing in other ruby versions, I'll correct it and reopen the pull request tomorrow

File: lib/rspec/expectations/failure_aggregator.rb [hunk 1]
```diff
@@ -150,11 +150,25 @@ def pluralize(noun, count)
...
           "#{index_label index}#{indented formatted_message, index}"
         end
       end
 
+      def exclusion_patterns
+        %w[/lib\d*/ruby/ bin/ exe/rspec /lib/bundler/ /exe/bundle:].map! { |s| Regexp.new(s.gsub('/', File::SEPARATOR)) }
+      end
+
+      def format_backtrace(backtrace)
+        backtrace&.map { |l| backtrace_line(l) }&.compact&.tap { |filtered| filtered.concat backtrace if filtered.empty? }
```
Comment (JonRowe) [inline lib/rspec/expectations/failure_aggregator.rb]: `&.` is not an operator we can use due to our supported Ruby versions, which is why this fails the build

**Comment by fabriciobedin** [comment]
Do you know how can I put some content as optional?
The lowers versions of Ruby don't show the block of the error.

Actually the code is like this 
```
describe "message formatting" do
      it "enumerates the failures with an index label and the path of each failure with a blank line in between" do
        expect {
          aggregate_failures do
            expect(1).to be_even
            expect(2).to be_odd
            expect(3).to be_even
          end
        }.to fail_including { dedent <<-EOS }
          |  1) expected `1.even?` to return true, got false
          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:259:in `block (5 levels) in <module:Expectations>'
          |
          |  2) expected `2.odd?` to return true, got false
          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:260:in `block (5 levels) in <module:Expectations>'
          |
          |  3) expected `3.even?` to return true, got false
          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:261:in `block (5 levels) in <module:Expectations>'
        EOS
      end
```

But the old versions needs to be like this
```
describe "message formatting" do
      it "enumerates the failures with an index label and the path of each failure with a blank line in between" do
        expect {
          aggregate_failures do
            expect(1).to be_even
            expect(2).to be_odd
            expect(3).to be_even
          end
        }.to fail_including { dedent <<-EOS }
          |  1) expected `1.even?` to return true, got false
          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:259
          |
          |  2) expected `2.odd?` to return true, got false
          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:260
          |
          |  3) expected `3.even?` to return true, got false
          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:261
        EOS
      end
```

Do you know how can I put this part `:in `block (5 levels) in <module:Expectations>'` as optional?

**Comment by JonRowe** [comment]
I think we strip that data in newer versions of Ruby on rspec-core giving a consistent output which is one option, another is to gate the cucumber scenario to different versions of ruby but I don't like that. You could write a new step that strips the info when processing the step, and in the specs you can just check the ruby version and interpolate the expected output.

File: spec/rspec/expectations/failure_aggregator_spec.rb [hunk 2]
```diff
@@ -262,10 +262,13 @@ def expect_error_included_in_aggregated_failure(error)
           end
         }.to fail_including { dedent <<-EOS }
           |  1) expected `1.even?` to return true, got false
+          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:259:in `block (5 levels) in <module:Expectations>'
```
Comment (JonRowe) [inline spec/rspec/expectations/failure_aggregator_spec.rb]: Typically we'd interpolate the end of these lines, e.g:
```suggestion
          |     ./spec/rspec/expectations/failure_aggregator_spec.rb:#{__LINE__  - 6}:in `block (5 levels) in <module:Expectations>'
```
So that changes to the files don't break the tests.

**Comment by fabriciobedin** [comment]
thank you very much @JonRowe, I'll try to do it

File: spec/rspec/expectations/failure_aggregator_spec.rb [hunk 3]
```diff
@@ -400,6 +415,19 @@ def expect_error_included_in_aggregated_failure(error)
...
         fail { |e| expect(e.message).to include(yield) }
       end
+
+      # Each Ruby version return a different exception complement.
+      # This method gets the current version and return the
+      # right complement.
+      def exception_complement(block_levels)
+        engine = RUBY_ENGINE || ''
+        version = RUBY_VERSION.gsub('ruby-', '') || '0'
+        if engine == 'ruby'
```
Comment (pirj) [inline spec/rspec/expectations/failure_aggregator_spec.rb]: I suggest using `RSpec::Support::Ruby.mri?`.

Comment (fabriciobedin) [reply spec/rspec/expectations/failure_aggregator_spec.rb]: thank you @pirj, it worked :)

**Comment by fabriciobedin** [comment]
What's the next steps? after merge, it'll be available on the next release, right?
Is there a date for the new release?

**Comment by pirj** [comment]
Do you mind to add this to the [`Changelog`](https://github.com/rspec/rspec-expectations/blob/master/Changelog.md) @fabriciobedin ?

We can squash and merge, or you can squash if you have a descriptive commit message in mind.

We release once in a while when there's a critical mass of things to release. It looks like we have a bunch things for 3.9.1. @JonRowe ?

**Comment by fabriciobedin** [comment]
I added to Changelog, thank you for remind me about it. :)

Is there some way to squash directly on Github? I never did it before could you help me please?

**Comment by pirj** [comment]
@fabriciobedin 
image

Yes, this can be done when merging.

File: spec/rspec/expectations/failure_aggregator_spec.rb [hunk 4]
```diff
@@ -400,6 +415,18 @@ def expect_error_included_in_aggregated_failure(error)
...
+      # This method gets the current version and return the
+      # right complement.
+      def exception_complement(block_levels)
+        version = RUBY_VERSION.gsub('ruby-', '') || '0'
+        if RSpec::Support::Ruby.mri?
+          version > '1.8.7' ? ":in `block (#{block_levels} levels) in <module:Expectations>'" : ''
+        else
+          version > '2.0.0' ? ":in `block in Expectations'" : ":in `Expectations'"
+        end
+      end
```
Comment (JonRowe) [inline spec/rspec/expectations/failure_aggregator_spec.rb]: Typically we define methods based on Ruby versions rather than perform run time changes, although these are tests I think I'd still rather have it more like this:
```suggestion
      if RSpec::Support::Ruby.mri? && RUBY_VERSION > "1.8.7"
        def exception_complement(block_levels)
          ":in `block (#{block_levels} levels) in <module:Expectations>'"
        end
      elsif RSpec::Support::Ruby.mri?
        def exception_complement(block_levels)
          ""
        end
      elsif RUBY_VERSION > "2.0.0"
        def exception_complement(block_levels)
          ":in `block in Expectations'"
        end
      else
        def exception_complement(block_levels)
          ":in `Expectations'"
        end
      end
```

File: lib/rspec/expectations/failure_aggregator.rb [hunk 5]
```diff
@@ -150,11 +150,27 @@ def pluralize(noun, count)
...
+      end
+
+      def format_backtrace(backtrace)
+        backtrace.map { |l| backtrace_line(l) }.compact.tap { |filtered| filtered.concat backtrace if filtered.empty? }
+      end
+
+      def backtrace_line(line)
+        return if [Regexp.union(RSpec::CallerFilter::IGNORE_REGEX, *exclusion_patterns)].any? { |p| line =~ p }
+
+        line.sub(/(\A|\s)#{File.expand_path('.')}(#{File::SEPARATOR}|\s|\Z)/, '\\1.\\2'.freeze).sub(/\A([^:]+:\d+)$/, '\\1'.freeze)
```
Comment (JonRowe) [inline lib/rspec/expectations/failure_aggregator.rb]: Can you add a comment as to what this is doing, just for clarity.

File: lib/rspec/expectations/failure_aggregator.rb [hunk 6]
```diff
@@ -150,11 +150,27 @@ def pluralize(noun, count)
...
           index += index_offset
-          formatted_message = yield exception
+          formatted_message = "#{yield exception}\n#{format_backtrace(exception.backtrace).first}"
           "#{index_label index}#{indented formatted_message, index}"
         end
       end
 
+      def exclusion_patterns
+        patterns = %w[/lib\d*/ruby/ bin/ exe/rspec /lib/bundler/ /exe/bundle:]
+        patterns << "org/jruby/" if RUBY_PLATFORM == 'java'
```
Comment (JonRowe) [inline lib/rspec/expectations/failure_aggregator.rb]: Prefer we use the jruby detection in `rspec-support`
```suggestion
        patterns << "org/jruby/" if RSpec::Support::Ruby.jruby?
```

File: Changelog.md [hunk 7]
```diff
@@ -14,6 +14,7 @@ Enhancements:
 * Improve `include` matcher's composability. (Phil Pirozhkov, #1155)
 * Mocks expectations can now set a custom failure message.
   (Benoit Tigeot and Nicolas Zermati, #1156)
+* The `aggregate_failures` method now shows the line path of each failure. (Fabricio Bedin, #1160)
```
Comment (JonRowe) [inline Changelog.md]: Grammatically this reads better (but also this is #1163)
```suggestion
* `aggregate_failures` now shows the backtrace line for each failure. (Fabricio Bedin, #1163)
```

**Comment by fabriciobedin** [comment]
Thank you @JonRowe for your suggestions, it really was good points.

**Comment by fabriciobedin** [comment]
Great @pirj  I tried to do the squash in my terminal but I think I did something wrong.

If you don't mind, you can select this squash option when you'll merge it, can be?

Thank you again for your help.

**Comment by pirj** [comment]
No worries, we've got you covered on that.

**Comment by fabriciobedin** [comment]
@JonRowe I saw this improvement and others one isn't in the 3.9.1 release. Is there something wrong?

**Comment by JonRowe** [comment]
Nothing is wrong, I classed this as an enhancement so needs to be released in a minor version, not a patch version according to our interpretation of semantic versioning. Minor versioning requires us to release all the gems simultaneously so they tend to be a bit longer in between as they need some coordination.

**Comment by fabriciobedin** [comment]
ahh.. I understood @JonRowe , so it'll only be able on 3.10.0 or 4.0.0 right?
Do you have some forecast of it?

**Comment by JonRowe** [comment]
Yep, only on `3.10.0` or `4.0.0`, I am likely to release `3.10.0` before starting work on RSpec `4.0.0` and after shipping `rspec-rails` 4.0.0` not committing to a direct time frame but in the next few weeks maybe.
